### ISSUE TITLE
Develop Plan for OA treatment

### ISSUE THREAD

**Issue by sr320** [laurahspencer/O.lurida_Stress#1]
@laurahspencer -
Please develop a written protocol for what will happen during the OA treatment portion. Be sure to include calibration of sensors and water chemistry sampling.

**Comment by laurahspencer** [comment]
@sr320 check out the rough draft of an OA treatment plan on my new [Google Doc draft](https://docs.google.com/document/d/1zQf4XiqQrEG0r3dHTzfgk2vP1jJ15giUT6SaqS0OTyc/edit?usp=sharing)... it's a rough sketch but will give us a good jumping off point for tomorrow afternoon.

**Comment by laurahspencer** [comment]
FYI @sr320: After mapping out 2 years of stress tests/spawning/separate groups, I realized that it is completely unrealistic to try to maintain separate stressor treatments. My new plan is to: each generation has 1 "stressed" group, and 1 "no-stress" group. The stressed group will be subjected to the 3 stressors (T, pH, mechanical), the other group will not (check this diagram below - click on it and zoom in to read). I could therefore have 1-3 culture tank/pH treatment this year, depending on space & which oysters I want to use.

![manchester oly exp](https://github.com/laurahspencer/LabNotebook/blob/master/images/Conceptual-Diagram.jpg?raw=true)

**Comment by sr320** [comment]
Lets clarify what oysters you have - particularly if Katherine's are
combined, as well as define phenotypes of Jakes

**Comment by laurahspencer** [comment]
Ok, this is pretty confusing! I've deduced the following from chatting with folks, PSRF photos, and from the helpful [schematic](https://docs.google.com/drawings/d/1xRNhsCgDO093FKyItvsMwl07NQQMTRQwHffvbVYB4IY/edit) that Grace made, and this google doc: [Fidalgo outplant @ Manchester](https://drive.google.com/drive/folders/0B_Kednl1tNImTjRzbHVMQkdOb1E)

 * **Three populations from Jake's oysters, all born 2014, and all out-planted at Fidalgo Bay:**  
      * 2SN 	→ Oyster Bay	origin			(South)  
      * 2NF	→ Fidalgo Bay origin			(North)  
      * 2HL	→ Dabob/Hood Canal origin		(Central)  
      * Then, they were all moved to Clam Bay (Manchester) for ~2yrs.  There are ~100 per group, 50 in each temperature treatment. 
 * **One F2 group from Katherine:** all born 2015 @ Manchester from one of Jake's oyster groups. The label says "SS", which seems to correspond to Oyster Bay; the question is, at which stage were they in Oyster Bay? There aren't any photos from when they were moved to the current system:
    * Are they F1's, from X(?) broodstock, ouplanted in Oyster Bay
    * Are they F1's from Oyster Bay, outplanted in Oyster Bay? 
    * Other?

**Comment by sr320** [comment]
I would say Katherine's were from broodstock that were grown out at Clam
Bay.

Issue with Katherine's is that the numbers might not match up. She should
have some from all population - how many of Katherines?

**Comment by laurahspencer** [comment]
I have 653 of Katherine's oysters, which are labeled "Katherine-SS-F2-2015"  (~325 in each temperature treatment at this point)
