### ISSUE TITLE
Use of P. generosa gonad transcriptome for Pecan

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/O.lurida_Stress#4]
To run Pecan with the goeduck data from Lumos, I need to use a protein database, which @emmats  and @sr320 said should be the gonad transcriptome. I'm exploring various geoduck gonad transcriptome files linked from the Robert's lab website [e.g.](https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP072283), but I'm not 100% sure which file is appropriate. Could you guys point me to what you were thinking I should use? Or give me hints?

**Comment by sr320** [comment]
Sure - to confirm you need a protein fasta file?

**Comment by sr320** [comment]
just to clarify - why is this in Olurida stress repo?

**Comment by emmats** [comment]
She will need to start with a fasta file.

**Comment by sr320** [comment]
Here is a Protein fasta file from Geoduck gonad transcriptome:

https://raw.githubusercontent.com/sr320/paper-pano-go/52c6b18b5b09e5c3a49250cf47ad4ddc8e9dc004/data-results/Geoduck-transcriptome-v2.transdecoder.pep

**Comment by laurahspencer** [comment]
Thank you!

Good question about the repo - I was in class and very distracted. I'll move this info over to the DNR repo.
