### ISSUE TITLE
Sample resources for RNA & DNA

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/O.lurida_Stress#5]
@sr320 

### This is the number of frozen larval samples I have:

  | Spawning Bucket Rep  | # Samples in -80 | Total # Larvae | Average larvae/sample
-- | -- | -- | -- | --
NF-10 Ambient | A  | 3 | 481,353 | 160,451
NF-10 Ambient | B  | 2 | 68,767 | 34,383
NF-10 Low | A  | 0 | - | #DIV/0!
NF-10 Low | B  | 2 | 157,117 | 78,558
NF-6 Ambient | A  | 1 | 60,600 | 60,600
NF-6 Ambient | B  | 1 | 85,433 | 85,433
NF-6 Low | A  | 4 | 336,685 | 84,171
NF-6 Low | B  | 3 | 416,150 | 138,717
SN-10 Ambient | A  | 6 | 941,697 | 156,949
SN-10 Ambient | B  | 7 | 390,723 | 55,818
SN-10 Low | A  | 2 | 32,900 | 16,450
SN-10 Low | B  | 6 | 692,407 | 115,401
SN-6 Ambient | A  | 1 | 107,100 | 107,100
SN-6 Ambient | B  | 6 | 840,283 | 140,047
SN-6 Low | A  | 4 | 399,900 | 99,975
SN-6 Low B |  B | 6 | 1,074,960 | 179,160
HL-10 Ambient | n/a  | 4 | 306,610 | 76,653
HL-10 Low | n/a  | 5 | 394,313 | 78,863
HL-6 Ambient | n/a  | 1 | 39,400 | 39,400
HL-6 Low | n/a  | 3 | 553,900 | 184,633
K-10 Ambient | n/a  | 3 | 27,843 | 9,281
K-10 Low | n/a  | 3 | 338,017 | 112,672
K-6 Ambient | n/a  | 4 | 163,777 | 40,944
K-6 Low | n/a  | 5 | 190,357 | 38,071

## In summary for South and North F1, I have the following # pooled larval samples for RNA-seq / Tag-seq:  

Treatment   Grp | # Samples in -80
-- | --
NF-10 Ambient | 5
NF-10 Low | 2
NF-6 Ambient | 2
NF-6 Low | 7
SN-10 Ambient | 13
SN-10 Low | 8
SN-6 Ambient | 7
SN-6 Low | 10
HL-10 Ambient | 4
HL-10 Low | 5
HL-6 Ambient | 1
HL-6 Low | 3
K-10 Ambient | 3
K-10 Low | 3
K-6 Ambient | 4
K-6 Low | 5

**NOTE: It is possible that some of these samples have >1 family, if >1 oyster spawned on the same day (but this is unlikely, since females spawn ~200k at a time)**

## Number of mantle/gill/adductor/gonad broodstock samples, for DNA-methylation: 
  * 9 of each tissue type, from each population/treatment  

## Number of juveniles at the dock, for DNA-methylation: 
  * North Ambient pH: 1,500  
  * North Low pH: 680    
  * South F1 Ambient pH: 125    
  * South F1 Low pH:  210   
  * South F1 mini-experiment Ambient pH:  
  * South F1 mini-experiment Low pH:

**Comment by sr320** [comment]
Lets start with gene expression.
Biggest concern is gene expression differences are associated with difference in development- we can presume OA impacts this....

Ideally it would be good to confirm similar stages would be compared. 

I am not seeing temporal sampling?

What would you suggest as the primary question in regard to this- and what would be the appropriate comparison to make?

**Comment by sr320** [comment]
re DNA methylation- 
if went this way - minimum sampling IMO 
two parental samples per treatment (OA-control) = 4 (same sex)
1 larval sample (pool from each parent) = 4
8*400 = 3200 + 2500 (seq) = $5700

**Comment by laurahspencer** [comment]
All larval samples in -80 were collected/frozen the day they were released, so all larvae are <1 day old (after leaving brood chamber).  I did not collect larval samples as they grew, so no temporal assessment of gene expression. 

No pH treatments occurred while broodstock were spawning or larvae were developing, so any day 1 developmental differences would be due to maternal effects. They should all be at the same stage. 

Re: gene expression

Questions are: 
  - Why was survival _higher_ in South Sound larvae from low-pH broodstock (as compared to ambient pH broodstock, and as compared to North Sound response)?  
    * This pattern was observed in the SS-F1, SS-F2 _and_ SS-F1 mini-experiment; indicates a genetic component to fitness under low pH  
 - Which biological functions / genes are upregulated in South Sound broodstock in low pH, compared to those in ambient pH _and_ compared to North Sound in low pH?   
 - Are any genes/functions differentially expressed between SS and NS larvae in low pH at day 1 that makes them differentially equipped for the larval stage?  
  - Are day1 larval lipid stores different between treatment and population?  

Possible comparisons: 
  - SS and NS broodstock gene expression in low pH and control pH, tissue TBD (gonad, gill, mantle)  (4 treatments) 
 -  SS and NS larvae (parental pool) gene expression in low pH and control pH
 - SS and NS larvae lipid content

**Comment by sr320** [comment]
Actually the chances of seeing differences in gene expression are low, given no "stress" at day 1.

**Continue process to extract DNA for methylation of parents and offspring..**

A RNA-seq exp could be 

the four larval samples? SS/NS (parents in low ph and control)- seems like you have replicate buckets (that is different parents). Thus 8 samples.
8*400=3200 library prep + 5000 seq = 8200.

**Comment by laurahspencer** [comment]
Do you not share my concerns over the gonad stage/tissue isolation?  With n=2 samples / treatment, I can focus on ripe females - primary concern is accidentally getting other tissue types... 

Methylation in offspring could be assessed in either:  
  * 1-day old larval samples (pooled by parent), or  
  * 1-yr old seed (at dock) to see if methylation patterns persist. However, not sure which tissue to use in seed (since gonad isolation would be very difficult, as it will be tiny)  

Also, methylation question will change my design.  I will focus on the North Sound group, where survival was _much_ lower in low pH group, so we can focus on original question: does pH-induce a change in methylation, and does it carry to and persist in 2nd generation?  Can re-run experiment with seed next winter.

**Comment by sr320** [comment]
Can discuss - but no, getting other tissue is not a concern.
Whole seed would be preferred.
Hall is main thing to consider now..
I do no see any value in re-running experiments....

**Comment by sr320** [comment]
Can this be closed?

**Comment by laurahspencer** [comment]
Yes, can be closed.
